### ISSUE TITLE
bootcamp issues

### ISSUE THREAD

**Issue by axcell-0** [enocol/Review#3]
This is a project created for my bootcamp project please all the comment are highly welcome

**Comment by axcell-0** [comment]
nice work  your code is clean well readable but please try to used semantic tags.

**Comment by Bettenoch** [comment]
Your tribute page is nice but it would be better if you use different font sizes/font-types for the list items and headings

**Comment by enocol** [comment]
Thank you all for your comments and all comments have been taken into consideration and will be acted upon.
